server.port=8083
spring.application.name=communication-service

# Connexion à la base dédiée créée sur Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/db_communication
spring.datasource.username=postgres
spring.datasource.password=mon_mot_de_passe

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

