server.port=8084
spring.application.name=budget-service

spring.datasource.url=jdbc:postgresql://localhost:5432/db_budget
spring.datasource.username=postgres
spring.datasource.password=mon_mot_de_passe

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

